version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    user: "${UID}:${GID}"
    working_dir: /app
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379/1
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_ENV=development
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

volumes:
  db_data:
  redis_data:
